//! ITfTextInputProcessorEx implementation — the main TSF entry point.

use std::cell::RefCell;
use std::rc::Rc;

use windows::Win32::Foundation::*;
use windows::Win32::UI::TextServices::*;
use windows::core::*;

use crate::candidate::window::CandidateWindow;
use crate::engine_bridge::EngineBridge;
use crate::globals::{
    GUID_DISPLAY_ATTRIBUTE_CONVERTED, GUID_DISPLAY_ATTRIBUTE_INPUT, GUID_PRESERVED_KEY_ONOFF,
    dll_add_ref, dll_release,
};
use crate::tsf::compartment;
use crate::tsf::lang_bar::KarukanLangBarButton;

/// The main karukan text service COM object.
///
/// Implements ITfTextInputProcessorEx (and its base ITfTextInputProcessor),
/// ITfKeyEventSink, ITfCompositionSink, and ITfDisplayAttributeProvider.
#[implement(
    ITfTextInputProcessorEx,
    ITfTextInputProcessor,
    ITfKeyEventSink,
    ITfCompositionSink,
    ITfDisplayAttributeProvider,
    ITfThreadMgrEventSink,
    ITfCompartmentEventSink
)]
pub struct KarukanTextService {
    pub(crate) inner: RefCell<KarukanTextServiceInner>,
}

pub(crate) struct KarukanTextServiceInner {
    pub(crate) thread_mgr: Option<ITfThreadMgr>,
    pub(crate) client_id: u32,
    pub(crate) engine: EngineBridge,
    pub(crate) composition: Option<ITfComposition>,
    /// Cookie for ITfThreadMgrEventSink
    pub(crate) thread_mgr_sink_cookie: u32,
    /// Cookie for ITfKeyEventSink
    pub(crate) keystroke_mgr_cookie: bool,
    /// Cookie for ITfCompartmentEventSink on GUID_COMPARTMENT_KEYBOARD_OPENCLOSE
    pub(crate) compartment_sink_cookie: u32,
    /// Cached EngineResult from OnTestKeyDown for reuse in OnKeyDown
    pub(crate) cached_result: Option<karukan_im::EngineResult>,
    /// Whether the IME is enabled (toggled via PreservedKey)
    pub(crate) enabled: bool,
    /// Candidate window for displaying conversion candidates
    pub(crate) candidate_window: Option<Rc<RefCell<CandidateWindow>>>,
    /// Language bar button for mode display
    pub(crate) lang_bar_item: Option<ITfLangBarItemButton>,
    /// Display attribute atom for input (composing) text
    pub(crate) display_attr_atom_input: u32,
    /// Display attribute atom for converted text
    pub(crate) display_attr_atom_converted: u32,
    /// Previous input mode — tracked to detect mode changes for Language Bar updates
    pub(crate) prev_input_mode: karukan_im::InputMode,
}

#[allow(clippy::new_without_default)]
impl KarukanTextService {
    pub fn new() -> Self {
        dll_add_ref();
        Self {
            inner: RefCell::new(KarukanTextServiceInner {
                thread_mgr: None,
                client_id: 0,
                engine: EngineBridge::new(),
                composition: None,
                thread_mgr_sink_cookie: TF_INVALID_COOKIE,
                keystroke_mgr_cookie: false,
                compartment_sink_cookie: TF_INVALID_COOKIE,
                cached_result: None,
                enabled: true,
                candidate_window: None,
                lang_bar_item: None,
                display_attr_atom_input: 0,
                display_attr_atom_converted: 0,
                prev_input_mode: karukan_im::InputMode::Hiragana,
            }),
        }
    }
}

impl KarukanTextService_Impl {
    /// Expose `cast()` as `pub(crate)` so other modules (e.g. key_event_sink) can obtain
    /// COM interfaces from the service. The `cast()` generated by `#[implement]` is private.
    pub(crate) fn cast_interface<T: windows::core::Interface>(&self) -> windows::core::Result<T> {
        unsafe { self.cast() }
    }
}

impl Drop for KarukanTextService {
    fn drop(&mut self) {
        dll_release();
    }
}

// ITfTextInputProcessor implementation
impl ITfTextInputProcessor_Impl for KarukanTextService_Impl {
    fn Activate(&self, ptim: Option<&ITfThreadMgr>, tid: u32) -> Result<()> {
        self.ActivateEx(ptim, tid, 0)
    }

    fn Deactivate(&self) -> Result<()> {
        let mut inner = self.inner.borrow_mut();

        // Save learning cache before deactivation
        inner.engine.save_learning();

        // Unadvise key event sink
        if inner.keystroke_mgr_cookie {
            if let Some(ref thread_mgr) = inner.thread_mgr {
                unsafe {
                    let keystroke_mgr: Result<ITfKeystrokeMgr> = thread_mgr.cast();
                    if let Ok(km) = keystroke_mgr {
                        let _ = km.UnadviseKeyEventSink(inner.client_id);
                        // Unpreserve key
                        let pk = TF_PRESERVEDKEY {
                            uVKey: 0x19, // VK_KANJI (Hankaku/Zenkaku)
                            uModifiers: 0,
                        };
                        let _ = km.UnpreserveKey(&GUID_PRESERVED_KEY_ONOFF, &pk);
                    }
                }
            }
            inner.keystroke_mgr_cookie = false;
        }

        // Unadvise thread manager event sink
        if inner.thread_mgr_sink_cookie != TF_INVALID_COOKIE {
            if let Some(ref thread_mgr) = inner.thread_mgr {
                unsafe {
                    let source: Result<ITfSource> = thread_mgr.cast();
                    if let Ok(src) = source {
                        let _ = src.UnadviseSink(inner.thread_mgr_sink_cookie);
                    }
                }
            }
            inner.thread_mgr_sink_cookie = TF_INVALID_COOKIE;
        }

        // Unadvise compartment event sink
        if inner.compartment_sink_cookie != TF_INVALID_COOKIE {
            if let Some(ref thread_mgr) = inner.thread_mgr {
                let _ = compartment::unadvise_keyboard_openclose(
                    thread_mgr,
                    inner.client_id,
                    inner.compartment_sink_cookie,
                );
            }
            inner.compartment_sink_cookie = TF_INVALID_COOKIE;
        }

        // Remove language bar item
        if let Some(lang_bar_item) = inner.lang_bar_item.take()
            && let Some(ref thread_mgr) = inner.thread_mgr
        {
            unsafe {
                let lang_bar_mgr: Result<ITfLangBarItemMgr> = thread_mgr.cast();
                if let Ok(mgr) = lang_bar_mgr {
                    let _ = mgr.RemoveItem(&lang_bar_item);
                }
            }
        }

        // Drop active composition reference (TSF handles cleanup)
        inner.composition = None;

        // Destroy candidate window
        if let Some(cw) = inner.candidate_window.take() {
            cw.borrow_mut().destroy();
        }

        inner.engine.reset();
        inner.thread_mgr = None;
        inner.client_id = 0;
        inner.enabled = true;

        Ok(())
    }
}

// ITfTextInputProcessorEx implementation
impl ITfTextInputProcessorEx_Impl for KarukanTextService_Impl {
    fn ActivateEx(&self, ptim: Option<&ITfThreadMgr>, tid: u32, _dwflags: u32) -> Result<()> {
        let mut inner = self.inner.borrow_mut();

        let thread_mgr = ptim.ok_or(E_INVALIDARG)?;
        inner.thread_mgr = Some(thread_mgr.clone());
        inner.client_id = tid;

        // Initialize the engine (loads models, dictionaries, learning cache)
        if let Err(e) = inner.engine.initialize() {
            tracing::error!("Failed to initialize engine: {}", e);
            // Continue anyway — engine works without models (romaji-only mode)
        }

        // Register display attribute atoms via ITfCategoryMgr
        unsafe {
            if let Ok(cat_mgr) = windows::Win32::System::Com::CoCreateInstance::<_, ITfCategoryMgr>(
                &CLSID_TF_CategoryMgr,
                None,
                windows::Win32::System::Com::CLSCTX_INPROC_SERVER,
            ) {
                if let Ok(atom_input) = cat_mgr.RegisterGUID(&GUID_DISPLAY_ATTRIBUTE_INPUT) {
                    inner.display_attr_atom_input = atom_input;
                }
                if let Ok(atom_converted) = cat_mgr.RegisterGUID(&GUID_DISPLAY_ATTRIBUTE_CONVERTED)
                {
                    inner.display_attr_atom_converted = atom_converted;
                }
                tracing::debug!(
                    "Display attribute atoms: input={}, converted={}",
                    inner.display_attr_atom_input,
                    inner.display_attr_atom_converted
                );
            }
        }

        // Create candidate window
        inner.candidate_window = Some(Rc::new(RefCell::new(CandidateWindow::new())));

        // Advise key event sink
        unsafe {
            let keystroke_mgr: ITfKeystrokeMgr = thread_mgr.cast()?;
            let this_sink: ITfKeyEventSink = self.cast()?;
            keystroke_mgr.AdviseKeyEventSink(tid, &this_sink, TRUE)?;

            // Register preserved key: Hankaku/Zenkaku (VK_KANJI = 0x19) for IME toggle
            let pk = TF_PRESERVEDKEY {
                uVKey: 0x19, // VK_KANJI
                uModifiers: 0,
            };
            let desc: Vec<u16> = "karukan IME toggle".encode_utf16().collect();
            let _ = keystroke_mgr.PreserveKey(tid, &GUID_PRESERVED_KEY_ONOFF, &pk, &desc);

            inner.keystroke_mgr_cookie = true;
        }

        // Advise thread manager event sink
        unsafe {
            let source: ITfSource = thread_mgr.cast()?;
            let this_sink: ITfThreadMgrEventSink = self.cast()?;
            let cookie = source.AdviseSink(&ITfThreadMgrEventSink::IID, &this_sink)?;
            inner.thread_mgr_sink_cookie = cookie;
        }

        // Add language bar button
        unsafe {
            let lang_bar_mgr: Result<ITfLangBarItemMgr> = thread_mgr.cast();
            if let Ok(mgr) = lang_bar_mgr {
                let button = KarukanLangBarButton::new();

                // Set toggle callback: clicking the button toggles IME open/close
                let toggle_thread_mgr = thread_mgr.clone();
                let toggle_client_id = tid;
                button.set_toggle_callback(Box::new(move || {
                    if let Ok(open) =
                        compartment::get_openclose_state(&toggle_thread_mgr, toggle_client_id)
                    {
                        let _ = compartment::set_openclose_state(
                            &toggle_thread_mgr,
                            toggle_client_id,
                            !open,
                        );
                    }
                }));

                let item: ITfLangBarItemButton = button.into();
                if mgr.AddItem(&item).is_ok() {
                    inner.lang_bar_item = Some(item);
                    tracing::debug!("Language bar item added");
                }
            }
        }

        // Advise compartment event sink for keyboard open/close
        unsafe {
            let this_sink: ITfCompartmentEventSink = self.cast()?;
            match compartment::advise_keyboard_openclose(thread_mgr, inner.client_id, &this_sink) {
                Ok(cookie) => {
                    inner.compartment_sink_cookie = cookie;
                    // Set initial open state
                    let _ = compartment::set_openclose_state(thread_mgr, inner.client_id, true);
                }
                Err(e) => {
                    tracing::warn!("Failed to advise compartment sink: {:?}", e);
                }
            }
        }

        inner.enabled = true;

        Ok(())
    }
}

// ITfCompartmentEventSink implementation — syncs keyboard open/close state
#[allow(clippy::not_unsafe_ptr_arg_deref)]
impl ITfCompartmentEventSink_Impl for KarukanTextService_Impl {
    fn OnChange(&self, rguid: *const GUID) -> Result<()> {
        unsafe {
            if rguid.is_null() {
                return Ok(());
            }
            if *rguid != GUID_COMPARTMENT_KEYBOARD_OPENCLOSE {
                return Ok(());
            }
        }

        let mut inner = self.inner.borrow_mut();
        if let Some(ref thread_mgr) = inner.thread_mgr {
            match compartment::get_openclose_state(thread_mgr, inner.client_id) {
                Ok(open) => {
                    let was_enabled = inner.enabled;
                    inner.enabled = open;

                    if was_enabled && !open {
                        // IME closed: commit pending text and reset
                        let _committed = inner.engine.commit();
                        inner.engine.reset();
                        inner.composition = None;
                        if let Some(ref cw) = inner.candidate_window {
                            cw.borrow_mut().hide();
                        }
                    }

                    // Update language bar
                    if let Some(ref item) = inner.lang_bar_item {
                        let button: &KarukanLangBarButton =
                            unsafe { windows::core::AsImpl::as_impl(item) };
                        button.update_mode(inner.engine.input_mode(), inner.enabled);
                    }

                    tracing::debug!("Compartment OnChange: enabled={}", inner.enabled);
                }
                Err(e) => {
                    tracing::warn!("Failed to get openclose state: {:?}", e);
                }
            }
        }

        Ok(())
    }
}
